### ISSUE TITLE
new Home page for community website

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/threefold-friends#14]
after changing from ambassadors to community we need new content reflecting employees, contributors, .. etc

**Comment by Sacha96** [comment]
what kind of new content do you need?

**Comment by xmonader** [comment]
> what kind of new content do you need?

Currently the home page is addressing ambassadors, we need more suitable content for the home page of community, more inclusive, not just ambassadors, no?


![image](https://user-images.githubusercontent.com/64129/84406431-ccddea00-ac09-11ea-9c9c-a51883e0ed94.png)

**Comment by Sacha96** [comment]
I would just change 'our ambassadors are people who support us' to 'our community supports' for now.
